title: JohnJonesFour
email: johnjones4@gmail.com
description: "John Jones is the Vice President of Interactive Strategies at The Case Foundation and a technologist in Washington DC."
url: "https://johnjonesfour.com"
markdown: kramdown
permalink: pretty
paginate: 10
exclude: ["s3_website.yml","Readme.md"]
gems: ["jekyll-paginate","jekyll-minimagick"]

links:
- src: "https://github.com/johnjones4"
  name: "github"
- src: "https://twitter.com/johnjones4"
  name: "twitter"
- src: "https://www.linkedin.com/in/johnjones4"
  name: "linkedin"
- src: "https://www.facebook.com/johnjones4"
  name: "facebook"

collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  style: compressed

mini_magick:
  og:
    source: img/posts
    destination: img/og/posts
    resize: "1200x630"
  twitter:
    source: img/posts
    destination: img/twitter/posts
    resize: "280x150"
