AWSTemplateFormatVersion: "2010-09-09"
Description: JohnJonesFour.com Deployment Bot
Resources:
  DeploymentBotRole:
    Type: AWS::IAM::Group
    Properties: 
      Policies:
        - PolicyName: DeploymentBotSQSRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:*
                Resource: 
                  - "*"
        - PolicyName: DeploymentBotS3Role
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: 
                  - "*"
        - PolicyName: DeploymentBotCloufrontRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudfront:*
                Resource: 
                  - "*"
        - PolicyName: DeploymentBotLambdaRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:*
                Resource: 
                  - "*"
        - PolicyName: DeploymentBotLogRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: 
                  - "*"
        - PolicyName: DeploymentBotAPIGatewayRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:*
                Resource: 
                  - "*"
        - PolicyName: DeploymentBotCloudformationRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: 
                  - "*"
        - PolicyName: DeploymentBotIAMRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:*
                Resource: 
                  - "*"
